name: acars_aggregation_server
version: 0.0.1
dependencies:
  args: ^1.5.2
  angel_orm: ^2.0.2
  angel_orm_postgres: ^1.0.0
  convert:
  json_annotation: ^3.0.1
  nats:
    git: https://github.com/c16a/nats-dart.git
  quick_log: 0.4.0
  udp: ^3.0.1
dev_dependencies:
  angel_orm_generator: ^2.0.5
  build_runner: ^1.7.3
  json_serializable: ^3.2.5
