name: airframes_aggregation_server
version: 0.2.3
environment:
  sdk: '>=2.10.0 <3.0.0'
dependencies:
  args: ^1.5.2
  angel_orm: ^2.0.2
  angel_orm_postgres: ^1.0.0
  convert:
  json_annotation: ^3.0.1
  nats:
    git: https://github.com/c16a/nats-dart.git
  quick_log: ^0.4.0
  udp: ^3.0.2
  # dart_json_mapper: ^1.5.20
  async: ^2.2.0
  grpc: ^2.8.0
  protobuf: ^1.1.0
  dart_express: ^0.5.3
dev_dependencies:
  analyzer: 0.39.10
  angel_orm_generator: ^2.0.5
  build_runner: ^1.7.3
  json_serializable: ^3.2.5
dependency_overrides:
  http_multi_server: 2.2.0
  postgres: 2.1.1
